name: 'Run Test Cases'

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python and Pip
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: '3.8'
      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip
      - name: Install Python dependencies
        run: pip3 install -r requirements.txt
      - name: Build CPE dictionary
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: NVD_API_KEY=$NVD_API_KEY python3 cpe_search.py -u
      - name: Run test cases
        run: python3 test.py
