name: 'Run Test Cases'

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update
        run: sudo apt-get update
      - name: Get CPEs
        run: sudo ./cpe_search.py -u -v 2.3
      - name: Testing
        run: sudo ./test.py