name: 'Run Test Cases'

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update
        run: sudo apt-get update
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          version: '3.8'
      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip
      - name: Install Dependencies
        run: pip3 install -r requirements.txt
      - name: Get CPEs
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: NVD_API_KEY=$NVD_API_KEY python3 cpe_search.py -u
      - name: Testing
        run: python3 test.py